apiVersion: v1
kind: Service
metadata:
  name: cert-manager-demo-v2
  namespace: default
  labels:
    app: cert-manager-demo-v2
    repo: none
    product: demo
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9913'
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: nginx-vts-exporter
      port: 9913
      protocol: TCP
      targetPort: 9913
  selector:
    app: cert-manager-demo-v2
    repo: none
    product: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-demo-v2
  namespace: default
  labels:
    app: cert-manager-demo-v2
    repo: none
    product: demo
  annotations:
    configmap.reloader.stakater.com/reload: "cert-manager-demo-v2-global-config,cert-manager-demo-v2-virtual-host-config"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager-demo-v2
      repo: none
      product: demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: cert-manager-demo-v2
        repo: none
        product: demo
    spec:
      restartPolicy: Always
      containers:
      - name: cert-manager-demo-v2
        image: winds6206/nginx-vts:1.22.0
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          timeoutSeconds: 2
        volumeMounts:
          - name: cert-manager-demo-v2-virtual-host-config
            mountPath: /etc/nginx/conf.d
          - name: cert-manager-demo-v2-global-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      - name: nginx-vts-exporter
        image: sophos/nginx-vts-exporter:v0.10.7
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9913
        resources:
          requests:
            cpu: "0.5m"
            memory: "10Mi"
      volumes:
      - name: cert-manager-demo-v2-virtual-host-config
        configMap:
          name: cert-manager-demo-v2-virtual-host-config
      - name: cert-manager-demo-v2-global-config
        configMap:
          name: cert-manager-demo-v2-global-config
          items:
          - key: nginx.conf
            path: nginx.conf
