apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: cert-manager-demo-external-ingress-http2https
  namespace: default
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: "301"
